port: 7880
bind_addresses:
  - ""
prometheus:
  port: 7890
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true
  node_ip: 54.175.40.232
  enable_loopback_candidate: false
redis:
  address: localhost:6379
  username: ""
  password: ""
  db: 0
  use_tls: false
  sentinel_master_name: ""
  sentinel_username: ""
  sentinel_password: ""
  sentinel_addresses: []
  cluster_addresses: []
  max_redirects: null
turn:
  enabled: true
  domain: inapp-turn-test.kasookoo.ai
  tls_port: 5349
  udp_port: 3478
  external_tls: true
ingress:
  rtmp_base_url: rtmp://inapp-test.kasookoo.ai:1935/x
  whip_base_url: https://inapp-whip-test.kasookoo.ai/w
keys:
  APIDnfJj67ghFUY: dhSrBCmoKmy0l8GhItHCklqDwAaNneZJXPiLZEcnsJT
webhook:
  api_key: APIDnfJj67ghFUY
  urls:
    - https://sdk-test.kasookoo.ai/api/v1/sdk/webhooks/livekit
logging:
  level: info
  sample: false
  json: true
