apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kasookoo

resources:
  - namespace.yaml
  - kasookoo-sdk-backend/deployment.yaml
  - kasookoo-sdk-backend/service.yaml
  - kasookoo-sdk-backend/hpa.yaml
  - caddy/caddy-configmap.yaml
  - caddy/caddy-deployment.yaml
  - caddy/caddy-service.yaml

commonLabels:
  app.kubernetes.io/name: kasookoo-sdk-backend
  app.kubernetes.io/component: api

images:
  - name: kasookoo-sdk-backend
    newName: YOUR_REGISTRY/kasookoo-sdk-backend
    newTag: latest
