apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasookoo-sdk-backend
spec:
  template:
    spec:
      containers:
        - name: api
          volumeMounts:
            - name: firebase-credentials
              mountPath: /app/app/credentials/firebase-service-account.json
              subPath: firebase-service-account.json
              readOnly: true
      volumes:
        - name: firebase-credentials
          secret:
            secretName: kasookoo-sdk-backend-firebase
